format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PL360G55CF_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '20', y: '60', id: BSP_PL360G55CF_Evaluation_Kit}
