format_version: v1.0
type: UniqueComponent
attributes: {id: drvPlcPhy}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_PLC_BAND_IN_USE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '5'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_CD_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '31'}
  - type: Menu
    attributes: {id: DRV_PLC_COUP_G3_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: DRV_PLC_COUP_PRIME_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_LDO_EN_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '30'}
  - type: Combo
    attributes: {id: DRV_PLC_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: PL360}
  - type: String
    attributes: {id: DRV_PLC_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: FLEXCOM3}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_1CHN_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_PRIME_CH8}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: DRV_PLC_PRIME_CHANNELS_SELECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '253'}
  - type: Comment
    attributes: {id: DRV_PLC_PRIME_CHANNEL_WARN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: DRV_PLC_PROFILE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: PRIME}
  - type: File
    attributes: {id: DRV_PLC_PROFILE_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/plcPhy/drv_plc_phy_prime.h}
  - type: File
    attributes: {id: DRV_PLC_PROFILE_LOCAL}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/plcPhy/src/drv_plc_phy_local_prime.h}
  - type: File
    attributes: {id: DRV_PLC_PROF_FILE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/plcPhy/src/drv_plc_phy_prime.c}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_RESET_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '29'}
  - type: Boolean
    attributes: {id: DRV_PLC_THERMAL_MONITOR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PLC_SOURCE_BIN_G3_CENA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PLC_SOURCE_BIN_PRIME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_plc_phy_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: flexcom3}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: FLEXCOM3_SPI}
- type: ElementPosition
  attributes: {x: '589', y: '276', id: drvPlcPhy}
