/*******************************************************************************
  Secure Project System Configuration Header

  File Name:
    user_settings.h

  Summary:
    Build-time configuration header for the TrustZone secure system defined by 
    this project.

  Description:
    An MPLAB Project may have multiple configurations.  This file defines the
    build-time options for a single configuration.

  Remarks:
    This configuration header must not define any prototypes or data
    definitions (or include any files that do).  It only provides macro
    definitions for build-time configuration options

*******************************************************************************/

/*******************************************************************************
* Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/

//This file is used by WolfSSL to configure the build of the library
//NOTE:  Enabled by preprocessor directive WOLFCRYPT_USER_SETTINGS 
//       Otherwise, default build (Which will not work)
#ifndef WOLFCRYPT_USER_SETTINGS_H
#define WOLFCRYPT_USER_SETTINGS_H

//Include the WolfSSL configuration defines
#include "wolfcrypt_config.h"

/* ---------------------------------------------------------------------------
 * SAMD20 project overrides. This file is NOT regenerated by MCC, while
 * wolfcrypt_config.h IS -- so the minimal wolfCrypt build for this Service Node
 * lives here and survives regeneration. It trims the regenerated (full) config
 * back to exactly what the FU/PRIME security needs:
 *   - SHA-256        (FU image hash + Hash_DRBG RNG)
 *   - ECDSA P-256    (FU signature verification)
 *   - AES-128        (PRIME 1.4 security: CCM / CMAC / key wrap / ECB)
 *   - Hash_DRBG RNG  (SRV_RANDOM)
 * Besides saving flash, sizing ECC/SP math for 256 bits (not 521/4096) is the
 * binding RAM/stack constraint for the ECDSA verify on the SAMD20J18.
 * These overrides come AFTER the include so they win. 
 * --------------------------------------------------------------------------- */

/* --- Extra hashes not used --- */
#undef HAVE_SHA512
#undef WOLFSSL_SHA512
#undef WOLFSSL_SHA384
#undef WOLFSSL_SHA224
#undef WOLFSSL_SHA3
#undef HAVE_BLAKE2
#undef HAVE_BLAKE2B
#undef HAVE_BLAKE2S
#undef WOLFSSL_RIPEMD

/* --- Ciphers not used --- */
#undef HAVE_CAMELLIA
#undef HAVE_IDEA
#undef HAVE_HC128
#undef HAVE_RABBIT
#undef HAVE_CHACHA
#undef HAVE_POLY1305
#undef WOLFSSL_DES_ECB

/* --- AES: keep AES-128 ECB/CCM/CMAC/keywrap; drop the rest --- */
#undef WOLFSSL_AES_192
#undef WOLFSSL_AES_256
#undef HAVE_AES_CBC
#undef WOLFSSL_AES_COUNTER
#undef WOLFSSL_AES_CFB
#undef WOLFSSL_AES_OFB
#undef WOLFSSL_AES_XTS
#undef WOLFSSL_AES_EAX
#undef HAVE_AESGCM
#undef WOLFSSL_AESGCM_STREAM
#undef WOLFSSL_MIN_AUTH_TAG_SZ

/* --- Public-key / KDF not used --- */
#undef HAVE_X963_KDF
#undef HAVE_COMP_KEY
#undef HAVE_ECC_DHE
#undef HAVE_ECC521
#undef WOLFSSL_CUSTOM_CURVES
#undef WOLFSSL_OLD_PRIME_CHECK
#undef FP_ECC
#undef WC_ASYNC_ENABLE_RSA
#undef WC_RSA_NO_PADDING
#undef WC_RSA_PSS
#undef WOLFSSL_HAVE_SP_RSA

/* --- SP math: 256-bit only (drop 384/521/4096) --- */
#undef WOLFSSL_SP_384
#undef WOLFSSL_SP_521
#undef WOLFSSL_SP_4096

/* --- Cert buffers / anon not used --- */
#undef USE_CERT_BUFFERS_1024
#undef USE_CERT_BUFFERS_2048
#undef USE_CERT_BUFFERS_3072
#undef USE_CERT_BUFFERS_4096
#undef HAVE_ANON

/* --- ECC restricted to P-256, bignum sized for 256 bits, no RSA --- */
#undef  FP_MAX_BITS
#define FP_MAX_BITS 256
#define ECC_USER_CURVES
#define HAVE_ECC256
#define NO_RSA

#endif
