format_version: v1.0
configName: sam_e70_xult_pl460_rf215
folderName: sam_e70_xult_pl460_rf215
frameworkPath: C:\WORK\GIT\mh3
processor: ATSAME70Q21B
projectName: prime_phy_tester_tool_hybrid_sam_e70_xult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME70_DFP\4.9.129\same70b\atdf\ATSAME70Q21B.atdf
