package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "MH3-114158-update-prime-feedback-field"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_prime"
      type: "package"
      version: "dev"
    - name: "smartenergy_metrology"
      type: "package"
      version: "v1.0.0"
    - name: "usb"
      type: "package"
      version: "v3.16.0"
    - name: "shd"
      type: "package"
      version: "v1.2.0"
