package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_prime"
      type: "package"
      version: "v1.0.0"
    - name: "csp"
      type: "package"
      version: "v3.19.6"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"