package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_prime"
      type: "package"
      version: "SMS-4010-fix-required-misra-c-violations-in-prime-repo"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "usb"
      type: "package"
      version: "v3.14.0"
    - name: "touch"
      type: "package"
      version: "v3.16.0"
    - name: "shd"
      type: "package"
      version: "dev"
