package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "csp"
      type: "package"
      version: "v3.19.1"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
    - name: "crypto"
      type: "package"
      version: "dev"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "smartenergy"
      type: "package"
      version: "dev_v130"
    - name: "smartenergy_prime"
      type: "package"
      version: "dev"
