package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_prime"
      type: "package"
      version: "dev"
    - name: "smartenergy"
      type: "package"
      version: "dev"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "crypto_v4"
      type: "package"
      version: "v4.0.0-E3"
    - name: "usb"
      type: "package"
      version: "v3.14.0"
    - name: "touch"
      type: "package"
      version: "v3.16.0"
    - name: "shd"
      type: "package"
      version: "v1.0.0-E1"
