package:
  format-version: "1.0.0"
  name: "smartenergy_prime_apps"
  version: "v1.1.0-E1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_prime"
      type: "package"
      version: "v1.0.0-E1"
    - name: "usb"
      type: "package"
      version: "v3.14.0"
    - name: "shd"
      type: "package"
      version: "v1.0.0-E1"
