configVersion: 1.0.0
componentName: prime_config
coreVersion: 5.8.3
device: PIC32CX2051MTG128
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: prime_config
  type: module
  version: ''
- dependencyPackage: ''
  devMode: true
  name: smartenergy_prime
  type: package
  version: v1.1.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition:
    attributes:
      id: PRIME STACK
    children:
    - children:
      - attributes:
          id: prime_config
          x: '364'
          y: '21'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols:
    BN_SLAVE_EN:
      attributes:
        id: BN_SLAVE_EN
      children:
      - children:
        - attributes:
            id: prime_config
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    NUM_MAX_NODES:
      attributes:
        id: NUM_MAX_NODES
      children:
      - children:
        - attributes:
            id: prime_config
            value: '0'
          type: Dynamic
        type: Values
      type: Integer
    PRIME_FW_VERSION:
      attributes:
        id: PRIME_FW_VERSION
      children:
      - children:
        - attributes:
            id: visible
          children:
          - type: Value
            value: 'true'
          type: Boolean
        type: Attributes
      - children:
        - attributes:
            id: prime_config
            value: HS14.01.01
          type: Dynamic
        type: Values
      type: String
    PRIME_PROJECT:
      attributes:
        id: PRIME_PROJECT
      children:
      - children:
        - attributes:
            value: application project
          type: User
        type: Values
      type: Combo
  userData: {}
