configVersion: 1.0.0
componentName: srvSecurity
coreVersion: 5.8.4
device: PIC32CX2051MTG128
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: srvSecurity
  type: module
  version: ''
- dependencyPackage: ''
  devMode: true
  name: smartenergy
  type: package
  version: v1.5.1
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition:
    attributes:
      id: PRIME SERVICES
    children:
    - children:
      - attributes:
          id: srvSecurity
          x: '30'
          y: '100'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols: {}
  userData: {}
