format_version: v1.0
type: UniqueComponent
attributes: {id: srv_pserial}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SRV_PSER_PLC_PROFILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pserial, value: '3'}
      - type: User
        attributes: {value: '3'}
  - type: File
    attributes: {id: SRV_PSER_SOURCE_G3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: SRV_PSER_SOURCE_PRIME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '458', y: '179', id: srv_pserial}
