format_version: v1.0
type: UniqueComponent
attributes: {id: srv_psniffer}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SRV_PSNF_PLC_PROFILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_psniffer, value: '3'}
  - type: File
    attributes: {id: SRV_PSNF_SOURCE_G3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: SRV_PSNF_SOURCE_PRIME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '440', y: '262', id: srv_psniffer}
