configName: pl360g55cf_ek
folderName: pl360g55cf_ek
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAMG55J19
projectName: phy_tester_tool_pl360g55cf_ek
settings:
  PackageFilter: bsp;core;core_apps_sam_e70_s70_v70_v71;csp;csp_apps_pic32cx_bz24_bz25;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;dev_packs;mbed_os_rtos;mbed_os_rtos_apps;net;quick_docs;smartenergy;smartenergy_g3;smartenergy_g3_apps;smartenergy_prime;smartenergy_prime_apps;usb;usb_apps_device;wireless;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.5.65\samg55\atdf\ATSAMG55J19.atdf
